version: "3.3"
services:

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest

    volumes:
      - "./config:/config"
      - "/etc/localtime:/etc/localtime:ro"

    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

    #network_mode: host


