version: "3.4"
services:

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest

    volumes:
      - "./config:/config"
      - "/etc/localtime:/etc/localtime:ro"

    restart: always
    network_mode: host


