version: "3.4"
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest

    volumes:
      - "./config:/mosquitto/config"

    ports:
      - "1883:1883"
      - "9001:9001"

    restart: always


