version: '3.2'

  #volumes:
  #  nextcloud:
  #    driver_opts:
  #      type: "nfs"
  #      o: "addr=192.168.2.5,nolock,soft,rw,nfsvers=4,async"
  #      device: ":/export/dck_volumes/nextcloud"
  #volumes:
  #nextcloud:


services:
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: ./nextcloud
        target: /var/www/html
  
    env_file:
      - .environment

