version: "3.4"
services:

  wetty:
    container_name: wetty
    image: wettyoss/wetty

    labels:
      com.centurylinklabs.watchtower.enable: "false"


    ports:
      - "3000:3000"

    entrypoint:
      - yarn
      - start
      - --ssh-host=192.168.2.5
      - --base=/
      - --ssh-key=/key/wetty
      - --ssh-auth=publickey
      - --ssh-user=pupillo

    volumes:
      - type: bind
        source: ./key
        target: /key

    restart: always

