version: "3.4"
services:
  unifi-controller:
    image: jacobalberty/unifi:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - TZ='Europe/Rome'

    volumes:
      - ./data:/unifi/data
      - ./log:/unifi/log
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 8080:8080
      - 10001:10001/udp

    restart: unless-stopped

