version: "3.4"
services:

  apriporta:
    image: apriporta:latest

    labels:
      com.centurylinklabs.watchtower.enable: "false"

    container_name: apriporta

    env_file:
      - .environment

    restart: always
    network_mode: host


